<a href="https://colab.research.google.com/github/Um-king/orm/blob/main/lms_%EC%98%81%EC%83%81_%EA%B5%90%EC%9C%A1_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [2]:
data = [[1,2,3], [4,5,6], [7,8,9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a = a.astype(np.float32) # float형으로 형변환 -> a = a.astype('float32') 로 해도 동일
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [5]:
print(a[0][1])
print(a[0])

2.0
[1. 2. 3.]


In [6]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1, 10).reshape(3, 3)
# 3 * 3 행렬로 reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# np.arange(1, 13).reshape(3, 3) # Error -> 총 1~12까지 12개의 숫자를 출력하는데 3*3으로 만들려고해서 -> 12개의 숫자를 3*3=9로 만들려고하는것
np.arange(1, 13).reshape(3, 4)   # 숫자의 개수에 따라 reshape도 확인해야함 -> 개수를 맞춰야함

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# 3차원
np.arange(1, 13).reshape(3, 2, 2)
'''
array([[[ 1,  2],       # 맨 큰 괄호가 3개
        [ 3,  4]],      # 큰 괄호안에 2개 리스트
                        # 마지막 괄호에 2개의 원소  -> 3, 2, 2
       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])
'''

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [12]:
# None 값
print(np.nan) # float 형
print(np.nan * 10)

nan
nan


In [15]:
a = np.linspace(1, 10, 20) # 1~10까지 몇개를 만들 것인가. -> 20을 선언해서 20개가 만들어짐
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [16]:
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# 각각의 행렬위치의 원소끼리 합
data + data

# 파이썬 리스트는 연결이됨

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## 차원

In [22]:
# 0차원 : 스칼라
a = np.array(1)
print(a)
print(a.ndim)   # 몇차원인지
print(a.shape)  # 0차원은 shape이 없음

1
0
()


In [23]:
# 1차원 : 백터
a = np.array([1])
print(a)
print(a.ndim)
print(a.shape)

[1]
1
(1,)


In [24]:
# 1차원 : 백터
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)  # 5개의 형태를 가지고 있다.

[1 2 3 4 5]
1
(5,)


In [25]:
# 2차원 : 메트릭스
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.ndim)
print(a.shape) # 두개의 행과 세개의 열을 가지고 있다.

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [26]:
# 3차원 : 3차원 이상의 다차원의 행렬을 Tensor라고 부름
a = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(a)
print(a.ndim)
print(a.shape) # 두개의 행과 세개의 열을 가지고 있다.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


## 행렬(matrix)의 유형

In [27]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [28]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 집계 함수

In [30]:
 a= np.arange(10).reshape(2, 5)
 a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a[0][0] = 100
a[0, 1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [32]:
np.mean(a) # 평균

114.4

In [33]:
np.median(a) # 중앙 값

6.5

In [34]:
np.var(a) # 분산

87941.04

In [35]:
np.sum(a) # array의 원소 총합

1144

In [36]:
sum(a) # 같은 원소의 위치의 값을 합

array([ 105, 1006,    9,   11,   13])

In [38]:
# 축을 설정

print(np.sum(a, axis = 0)) # 같은 열 합산
print(np.sum(a, axis = 1)) # 같은 행 합산

[ 105 1006    9   11   13]
[1109   35]


# Pandas

In [39]:
import pandas as pd
import numpy as np

In [44]:
data = np.arange(0, 50, 10)
data

array([ 0, 10, 20, 30, 40])

In [45]:
a = pd.Series(data, index = ['a','b','c','d','e'])
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [46]:
# 인덱스를 설정하지 않으면 0부터 순서대로 자동으로 출력
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int64

In [47]:
a['b']

10

In [49]:
print(a.loc['b'])   # a의 명시적으로 선언한 'b'의 값을 출력
print(a.iloc[1])     # a의 1 인덱스 위치 출력

10
10


## 산술연산

In [52]:
a + 10
a + 10
a * 10
a ** 10
a / 5
a // 5
a % 2

a    0
b    0
c    0
d    0
e    0
dtype: int64

In [53]:
a > 15 # 15보다 큰값이 무엇인지 확인

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [55]:
# boolean 인덱싱

a[a > 15] # 15보다 큰 내역을 출력

c    20
d    30
e    40
dtype: int64

## 집계함수

In [56]:
a.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int64

In [57]:
a.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int64

In [58]:
a.mul(100)

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int64

In [59]:
a.div(100)

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [60]:
a.mod(100) # 나머지

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [61]:
print(a.min())
print(a.max())
print(a.min())
print(a.mean())
print(a.median()) # 중앙값

0
40
100


## DataFrame
엑셀, 스프레드 시트와 같은 것

In [62]:
rawData = np.random.randint(50, 100, size=(4, 3))
rawData

array([[75, 97, 60],
       [63, 63, 53],
       [86, 53, 67],
       [60, 76, 87]])

In [67]:
# 시트를 만든다

# rawData의 값을 index와 연결하고 각 colum의 title을 작성했다
df = pd.DataFrame(rawData, index = ['1반', '2반', '1반', '2반'], columns = ['국', '영', '수'])
df

국   영   수
1반  75  97  60
2반  63  63  53
1반  86  53  67
2반  60  76  87

In [68]:
# 국어점수만 출력
df['국']

# df[0] -> Error!

1반    75
2반    63
1반    86
2반    60
Name: 국, dtype: int64

In [71]:
# 새로운 컬럼에 평균값 추가
df['평균'] = round((df['국'] + df['영'] + df['수']) / 3, 2)
df

국   영   수     평균
1반  75  97  60  77.33
2반  63  63  53  59.67
1반  86  53  67  68.67
2반  60  76  87  74.33

In [72]:
df['na'] = np.nan
df

국   영   수     평균  na
1반  75  97  60  77.33 NaN
2반  63  63  53  59.67 NaN
1반  86  53  67  68.67 NaN
2반  60  76  87  74.33 NaN

In [73]:
# 컬럼을 통째로 지우는 방법

del df['na']
df

국   영   수     평균
1반  75  97  60  77.33
2반  63  63  53  59.67
1반  86  53  67  68.67
2반  60  76  87  74.33

In [74]:
# 평균이 75 이상인 것만
df[df.평균 > 75] # boolean 인덱싱

국   영   수     평균
1반  75  97  60  77.33

In [75]:
# 데이터 프레임은 평균으로 drop 하고 축은 columns으로 설정
df = df.drop(['평균'], axis = 'columns')
df # 평균 컬럼 삭제

국   영   수
1반  75  97  60
2반  63  63  53
1반  86  53  67
2반  60  76  87

## 결측값(nan) 처리

In [76]:
df = df.astype('float') # float 형변환
df

국     영     수
1반  75.0  97.0  60.0
2반  63.0  63.0  53.0
1반  86.0  53.0  67.0
2반  60.0  76.0  87.0

In [77]:
df['수'][2] = np.nan # 수학의 2번째 인덱스 값을 결측값으로 변경
df

국     영     수
1반  75.0  97.0  60.0
2반  63.0  63.0  53.0
1반  86.0  53.0   NaN
2반  60.0  76.0  87.0

In [79]:
# 원본을 수정하진 않음
df.dropna(axis=0) # 축을 설정 -> 0: row를 기준으로 없어짐 -> row 단위로 nan이 포함된 행을 삭제

국     영     수
1반  75.0  97.0  60.0
2반  63.0  63.0  53.0
2반  60.0  76.0  87.0

In [80]:
df # 원본 반영x

국     영     수
1반  75.0  97.0  60.0
2반  63.0  63.0  53.0
1반  86.0  53.0   NaN
2반  60.0  76.0  87.0

In [ ]:
# 원본을 수정하고 싶으면 inplace = True로 설정
# df.dropna(axis=0, inplace = True)

In [83]:
df.dropna(axis=1) # column단위로 삭제

국     영
1반  75.0  97.0
2반  63.0  63.0
1반  86.0  53.0
2반  60.0  76.0

In [84]:
# nan의 값을 수정
df.fillna('hello')

국     영      수
1반  75.0  97.0   60.0
2반  63.0  63.0   53.0
1반  86.0  53.0  hello
2반  60.0  76.0   87.0

In [85]:
df.fillna(0)

국     영     수
1반  75.0  97.0  60.0
2반  63.0  63.0  53.0
1반  86.0  53.0   0.0
2반  60.0  76.0  87.0

## MultiIndex

In [87]:
df.T # row와 column의 위치를 바꿈

1반    2반    1반    2반
국  75.0  63.0  86.0  60.0
영  97.0  63.0  53.0  76.0
수  60.0  53.0   NaN  87.0

In [88]:
# multi Index로 변환

df.index =[['1학년','1학년','2학년','2학년'], ['1반','2반','1반','2반']]
df

국     영     수
1학년 1반  75.0  97.0  60.0
    2반  63.0  63.0  53.0
2학년 1반  86.0  53.0   NaN
    2반  60.0  76.0  87.0

In [90]:
# colum에 multi index 적용
df.columns = [['언어', '언어', '수리'], ['국', '영', '수']]
df

언어          수리
           국     영     수
1학년 1반  75.0  97.0  60.0
    2반  63.0  63.0  53.0
2학년 1반  86.0  53.0   NaN
    2반  60.0  76.0  87.0

In [91]:
df['언어'] # 언어에 해당하는 내역들이 출력

국     영
1학년 1반  75.0  97.0
    2반  63.0  63.0
2학년 1반  86.0  53.0
    2반  60.0  76.0

In [92]:
df['언어']['국'] # 국어점수만 출력

1학년  1반    75.0
     2반    63.0
2학년  1반    86.0
     2반    60.0
Name: 국, dtype: float64

In [93]:
# row 값 출력
df.iloc[0] # iloc = index location

언어  국    75.0
    영    97.0
수리  수    60.0
Name: (1학년, 1반), dtype: float64

In [94]:
df.loc['1학년'] # 1학년만 출력

언어          수리
       국     영     수
1반  75.0  97.0  60.0
2반  63.0  63.0  53.0

In [95]:
df.loc['1학년'].loc['1반']

언어  국    75.0
    영    97.0
수리  수    60.0
Name: 1반, dtype: float64

## 데이터 사전 분석

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      float64
 1   (언어, 영)  4 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 384.0+ bytes


In [97]:
df.head() # 가장 처음부터의 5개 출력

언어          수리
           국     영     수
1학년 1반  75.0  97.0  60.0
    2반  63.0  63.0  53.0
2학년 1반  86.0  53.0   NaN
    2반  60.0  76.0  87.0

In [98]:
df.tail() # 가장 마지막부터의 5개 출력

언어          수리
           국     영     수
1학년 1반  75.0  97.0  60.0
    2반  63.0  63.0  53.0
2학년 1반  86.0  53.0   NaN
    2반  60.0  76.0  87.0

In [99]:
df.dtypes

언어  국    float64
    영    float64
수리  수    float64
dtype: object

In [100]:
df.describe()

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   71.000000  72.250000  66.666667
std    11.916375  18.997807  17.953644
min    60.000000  53.000000  53.000000
25%    62.250000  60.500000  56.500000
50%    69.000000  69.500000  60.000000
75%    77.750000  81.250000  73.500000
max    86.000000  97.000000  87.000000

In [101]:
# 결측값이 있는지 확인(nan이 있는지 확인)
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False   True
    2반  False  False  False

In [102]:
# 결측치가 몇개 있는지
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

## 값의 연결

In [103]:
a = pd.DataFrame(np.arange(1, 10).reshape(3, 3)) # 데이터 시트 생성
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [106]:
b = pd.Series(np.arange(10, 40, 10)) # 데이터 행렬? 내역 생성
b

0    10
1    20
2    30
dtype: int64

In [110]:
# 새로운 column 에다가 붙임
pd.concat([a, b], axis = 1) # 이렇게 하면 새로운 컬럼명이 0으로 됨(초기값)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [109]:
pd.concat([a, b], axis = 1, ignore_index = True) # 다음 컬럼을 따라감 (0,1,2 -> 그다음 3)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [111]:
# 새로운 행에 추가
a.append(b, ignore_index = True)

<ipython-input-111-aa06c5ef4eb4>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a.append(b, ignore_index = True)


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30