<a href="https://colab.research.google.com/github/Um-king/orm/blob/main/240119_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기본 역량 문제 풀이 20문제(프로그래머스 10개 + pyalgo 10개)


백준, 프로그래머스, 코딩도장, pyalgo

## 1. 짝수 홀수 개수

링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120824

In [ ]:
def solution(data):
    return data

solution()

In [ ]:
# 꼭 풀고 제출하여 점수 올리기!(로그인 후에 제출하면 정답여부 나오고 점수 올릴 수 있음 -> 깃허브와 연동하기)

# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120824
# 1. 프로그래머스 짝수 홀수 개수
# 1.1.

def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    print(홀수, 짝수) # 마스킹: 짝수인지 홀수인지 True, Flase로 호출
    return [sum(짝수), sum(홀수)] # 짝수 개수와 홀수 개수 반환

solution([1, 2, 3, 4, 5])

[True, False, True, False, True] [False, True, False, True, False]


[2, 3]

In [ ]:
# 1.1.
# 좋은 풀이는 아니다 -> sum은 순회하기 때문에 속도가 증가하는것.
# sum 함수는 해당 자료형안에 있는 원소들을 순회하며 값을 생성하는 것이기때문에 속도에 문제가 있을 수 있음
# data의 가변 최대치를 본다

def solution(data):
    짝수 = [i % 2 == 0 for i in data] # 여기서도 순회1
    return [sum(짝수), len(data) - sum(짝수)] # sum(짝수) 첫번째 인덱스에서 순회2, 두번째 인덱스 sum에서 순회3.

In [ ]:
# 이게 더 나은 코드
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    갯수 = sum(짝수)
    return [갯수, len(data) - 갯수]

In [ ]:
# 프로그래머스 짝수 홀수 개수
# 1.2.

def solution(data):
    count = 0
    for i in data:
        if i % 2 == 0:
            count += 1
    return [count, len(data)-count] #  짝수 개수를 구한 후 전체에 해당 COUNT를 빼면 홀수 개수

solution([1, 2, 3, 4, 5])

[2, 3]

In [ ]:
# 프로그래머스 짝수 홀수 개수
# 1.3. 가장 효율이 좋은 코드
def solution(num_list):
    answer = [0, 0]
    for i in num_list:
        answer[i % 2] += 1 # 0,1 번째 인덱스에 count를 증가 -> 2로 나눴을때 0과 1만 출력되니 0이면 짝수, 1이면 홀수의 인덱스 위치에 count 증가
    return answer

solution([1, 2, 3, 4, 5])

[2, 3]

## 2. 머쓱이보다 키 큰 사람
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120585

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120585
# 프로그래머스 머쓱이보다 키 큰 사람
# 2.1

def solution(array, height):
    count = 0
    for i in array:
        if i > height:
            count += 1
    return count

solution([149, 180, 192, 170], 167)

3

In [ ]:
# 이렇게 언패킹 해서 사용할 수 있는 것들은 언패킹 해주세요.
# 가독성이 좋아집니다!
def solution(data):
    array, height = data # 언패킹
    pass

solution([[149, 180, 192, 170], 167]) # 이렇게 사용된다면

In [ ]:
# 2.2 filter 사용
# filter는 len()가 없습니다! -> list로 형변환

# filter는 왜 len()가 없나요?
# filter는 순회 돌기 전까지 실행이 되지 않은 함수이면서
# for와 같이 순회를 돌아야 그때서야 각 원소 별로 접근해서
# 따라서 순회를 돌지 않은 상태이기 때문에 길이를 알 수 없음
# 주문만 하고 아직 제조되지 않은 커피..! => 커피를 달라고 소리쳐야(순회 또는 형변환) 그때야 제조가 된다.

def solution(array, height):
    return len(list(filter(lambda x: x > height, array)))

solution([149, 180, 192, 170], 167)

3

In [ ]:
# 2.3 map 사용
def solution(array, height):
    return sum(map(lambda x: x > height, array)) # x>height인것을 boolean값으로 반환하고 sum

solution([149, 180, 192, 170], 167)

3

In [ ]:
# 2.3 리스트 컨프리헨션 사용
def solution(array, height):
    return sum(i > height for i in array)

solution([149, 180, 192, 170], 167)

3

## 3. 숨어있는 숫자의 덧셈(1)

링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120851

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120851
# 숨어있는 숫자의 덧셈(1)
# 문자열은 소문자, 대문자 그리고 한자리 자연수로만 구성
# 3.1

def solution(my_string):
    result = 0
    for i in my_string:
        if i.isdigit():
            result += int(i)
    return result

solution("aAb1B2cC34oOp")

10

In [ ]:
# 3.2

# 효율적이진 않지만, 문법 복습 차원에서 작성

def solution(my_string):
    return list(filter(lambda x: x.isdigit(), list(my_string)))

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [ ]:
# 3.2

# isdigit에 ()가 있고 없고 차이

def solution(my_string):
    return list(filter(str.isdigit, list(my_string))) # 이렇게 문자가 정수인지 바로 확인 가능

# str.isdigit에서 ()가 없는 차이 => str이란 클래스의 isdigit을 가져온것, 클래스함수 호출

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [ ]:
# 3.2

# 효율적이진 않지만, 문법 복습 차원에서 작성

def solution(my_string):
    return sum(map(int, filter(str.isdigit, my_string))) # my_string 문자열을 하나씩 가져와서 이렇게 문자가 정수인지 바로 확인 가능
    # filter로 정수인지 확인하고 map을 통해 정수 형변환하고 합산..
solution("aAb1B2cC34oOp")

10

In [ ]:
# 3.3

# 효율적이진 않지만, 문법 복습 차원에서 작성

def solution(my_string):
    return sum(map(lambda x: int(x) if x.isdigit() else False, my_string)) # 숫자가 아닌건 False로 반환되고 False는 0이기 때문에 계산은 된다.

solution("aAb1B2cC34oOp")

10

In [ ]:
# r''에서 r은 raw를 뜻함 -> 날것이라는 뜻(실무에서 자주 쓰는 용어 raw)
# raw data를 전달해줘 => 가공하지 않은 순수 데이터를 달라는 얘기

r'hello\nworld' # \n : 이스케이프 문자
print('hello\nworld') # 줄바꿈이 된다.
print(r'hello\nworld')  # 날것 그대로 출력 즉 이스케이프문자까지 문자열로 출력하겠다.

hello
world
hello\nworld


In [ ]:
# 3.4
# 정규 표현식을 사용한 방법

import re

re.findall(r'[0-9]', "aAb1B2cC34oOp") # 숫자만 검색

['1', '2', '3', '4']

In [ ]:
# findall 사용 -> 패턴을 찾아냄

import re

def solution(s):
    return sum(map(int, re.findall(r'[0-9]', s)))

solution("aAb1B2cC34oOp")

10

In [ ]:
# sub 사용 -> 찾은 패턴을 변경

import re

def solution(s):
    return sum(map(int, (re.sub(r'[a-zA-Z]', '', s))))

solution('aAb1B2cC34oOp')

10

## 4. 암호해독
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120892

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120892
# 암호해독
# 4.1 (가장 좋은 정답)

'''
"dfjardstddetckdaccccdegk"	4	"attack" => 4칸씩 건너뛰면서 추출
"pfqallllabwaoclk"	2	"fallback" => 2칸씩 건너뛰면서 추출
'''

def solution(cipher, code):
    return cipher[code-1::code] # code - 1: index = 3인 a부터 시작

solution("dfjardstddetckdaccccdegk", 4) # 4칸씩 이동하면서 문자열을 추출

'attack'

In [ ]:
# 4.2 반복문 사용

def solution(cipher, code):
    count = 1
    for i in cipher:
        if count == code:
            print(i)
            count = 0
        count += 1

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [ ]:
# 4.3 enumerate 사용

def solution(cipher, code):
    count = 1
    for i, j in enumerate(cipher, 1):
        if i % code == 0:
            print(j)

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [ ]:
# 4.4
# 이런 풀이는 권하지 않는다.

def solution(cipher, code):
    result = ''
    for i in range(1, len(cipher) // 4 + 1):
        result += cipher[i * code - 1]
    return result

solution("dfjardstddetckdaccccdegk", 4)

'attack'

## 5. 3,6,9 게임
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120891

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120891
# 3,6,9 게임
# 5.1

def solution(order):
    order = str(order)
    return order.count('3') + order.count('6') + order.count('9')

solution(29423)

2

In [ ]:
# 5.2 정규식 사용

import re

def solution(order):
    order = str(order)
    return len(list(re.findall(r'[369]', order)))

solution(29423)


2

## 6. 중복된 문자 제거
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120888

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120888
# 중복된 문자 제거(공백도 중복되면 제거)
# 6.1

# 내가 풀이
def solution(my_string):
    l = ''
    for i in my_string:
        if i not in l:
            l += i
    return l

solution("people")

'peol'

In [ ]:
# 6.2
# set을 사용 -> set은 중복을 제거한 자료형
# 중복은 제거했지만 순서 보장이 안됨

# set을 사용하여 중복 제거 완료, 그러나 순서를 보장하지 않음!
# set(my_string) 출력결과: {'e', 'l', 'o', 'p'}
# 그럼 방법은..?

# 강사님 풀이 == 나의 풀이(동일)
def solution(s):
    answer = ''
    for i in s:
        if i not in answer:
            answer += i
    return answer

solution("people")

'peol'

In [ ]:
# 6.3
# 더 간략하게
# 딕셔너리 사용(fromkeys())

def solution(my_string):
    return dict.fromkeys(my_string) # 딕셔너리는 키의 중복이 안된다는 점을 이용! dict은 3.8부터 순서가 보장

solution("people")

{'p': None, 'e': None, 'o': None, 'l': None}

In [ ]:
# 6.4
# join과 딕셔너리 사용
def solution(my_string):
    return ''.join(dict.fromkeys(my_string))
    # 각 문자를 key로 만들고 딕셔너리를 생성 -> 딕셔너리는 키 중복이 안되기 때문에 문자가 고유값으로 등록됨
    # 그 후 ''로 키값들을 join  ->  dict를 for문을 돌았을 때 key값만 나오는 이유와 같다
solution('people')

'peol'

## 7. A로 B만들기
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120886

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120886
# A로 B만들기
# 7.1 내 풀이

# 역순만 확인하는것. -> 순서가 olleh처럼 일정하게 들어오면 상관없지만 olelh로 들어오면 오답인것.
# 하지만 순서를 어떻게든 바꾸면 hello를 만들 수 있으니깐 그렇게 되도록 해야함
def solution(before, after):
    return 1 if before[::-1] == after else 0

solution("olleh", "hello")

1

In [ ]:
# 7.2
# 강사님 답 -> 내 답과의 결과는 같은데 코테에 강사님 답은 통과인 이유
# 앞의 매개변수를 정렬해서 뒤의 매개변수와 같느냐 / 길이는 같다고 제한되어있으니깐
# 역순뿐 아니라 순서를 이것저것 바꿔서 어떻게든 만들수 있느냐 aplpe과 apple을 보면 aplpe을 어떻게든 순서를 바꾸면 apple을 만들 수 있음
# 따라서 리스트로 원소들을 정렬한 후에 서로 같은 지 확인해야함

def solution(before, after):
    # print(sorted(list(before))) # sorted로 정렬 후에 동일한 값인지 확인
    # print(sorted(list(after)))
    return 1 if sorted(list(before)) == sorted(list(after)) else 0

solution("olleh", "hello")

['e', 'h', 'l', 'l', 'o']
['e', 'h', 'l', 'l', 'o']


1

In [ ]:
# 7.3
# 위의 문제처럼 굳이 list로 형변환 후에 sorted()할 필요없이 바로 정렬하면 된다.
# 문제의 정답에 오류가 있는듯
def solution(before, after):
    if len(before) != len(after): # 예외처리는 앞에서 반드시 해주어야 합니다. 특히나 요소가 없거나 길이가 0인 경우
        return 0
    return 1 if sorted(before) == sorted(after) else 0

solution("olleh", "hello")

1

In [ ]:
# 7.4
# collections 을 활용

import collections


print(collections.Counter("olleh"))
collections.Counter("olleh") == collections.Counter("hello")  # 요소가 동일한지

Counter({'l': 2, 'o': 1, 'e': 1, 'h': 1})


True

In [ ]:
# 7.5 순회
# 리스트 활용

def solution(before, after):
    a = list(after)
    for i in before:
        if i in a:
            #print(a) # a에 값이 존재한다면 삭제
            a.remove(i) # a에 문자가 존재하는 확인하면서 지워나가는 것
        else:
            return 0

    if a: # a의 원소가 남아있다면
        return 0
    return 1

solution("olleh", "hello")

['h', 'e', 'l', 'l', 'o']
['h', 'e', 'l', 'l']
['h', 'e', 'l']
['h', 'e']
['h']


1

In [ ]:
# 회문

# 'hello' => 'elloh' => 'llohe'
# 'hello' => 'ohell' => 'lohel'
# collections.deque를 사용해서 풀면 쉽게 풀립니다.

# 문제1 'hello'를 앞뒤로 이동시켜 'llohe'를 만들 수 있나요?
# 'hellohello'

# 문제2 몇칸 이동했나요?
# 'hellohello'.index('llohe')

## 8. 저주의 숫자3
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120871

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120871
# 저주의 숫자3
# 3의 배수와 숫자 3을 사용하지 않습니다.(13 사용x, 3의 배수 사용x, 16은 사용 가능)


# 십진수    3숫자마을
# 1         1               # 1을 입력하면 1을 반환
# 2         2
# 3         4               # 3을 입력하면 3을 사용할 수 없으므로 3을 제외하고 그 다음 숫자 4를 반환
# 4         5
# 5         7               # 반환값 또한 3이나 3의 배수가 될 수 없으므로 6 제외
# 6         8               # 6이면 3의 배수를 사용할 수 없으므로 8 반환
# 7         10
# 8         11
# 9         14
# 10        16
# ...       ...


In [ ]:
# 풀이 방법
# 1. [True, True, False, ...] -> 조건을 만족하는 값을 확인하여 인덱스값 확인
# 2. filter(3이 들어가는 숫자 없애기, filter(3의 배수 없애기, [1,2,3,4,5,6,7,8,9,10])) -> 이게 더 쉬운 방법을 듯 싶다.

In [ ]:
# 8.1

# 3의 배수가 아니면서 문자열로 변환후에 3이란 문자를 포함하고 있지 않은 것들을 출력
l = list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(1000)))

# 입력이 15라면 25라는 숫자를 출력해야함
l[15 - 1]

25

In [ ]:
# 정답
# 제한은 100으로 되어있지만 충분한 숫자를 만들어줘야해서 100보다 큰 수를 입력해야한다.
# 3의 마을에서는 3이나 3의 배수를 사용하지 못하므로 반환값은 100보다 큰수가 나올 수밖에 없으므로 반환값을 100보다 훨씬 큰 수로 잡아야한다
# 40만 출력해도 76을 반환 -> 그럼 100이면 확실하게 100보다 큰 수를 반환하게 되어있음 -> 따라서 range(100)하면 99까지의 숫자밖에 출력이 안되니깐
# 100보다 큰 수를 넣어서 만들어야한다.
def solution(num):
    return list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(1000)))[num - 1]

solution(15)

25

In [ ]:
# 100을 넣었을때 반환되는 값을 확인하기 위한 리스트 내역 출력
def solution(num):
    l = []
    for i in range(1000):
        if i % 3 != 0:
            l.append(i)
        elif '3' not in str(i):
            l.append(i)
    print(l)

solution(15)

[0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 136, 137, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 232, 233, 235, 2

# 9. 진로순서 정하기
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120835

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120835
# 진로순서 정하기 -> 응급도가 높은 순으로
# 9.1

# emergency	    result
# [3, 76, 24]	[3, 1, 2]

def solution(emergency):
    sotred_emergency = sorted(emergency, reverse = True)
    return [sotred_emergency.index(i) + 1 for i in emergency]

solution([3, 76, 24])

In [5]:
emergency = [3, 76, 24]

sotred_emergency = sorted(emergency, reverse = True)
sotred_emergency # 출력 결과 = [76, 24, 3]

# 원하는 결과 : [3, 1, 2] -> 진료 순서 // 응급도 76이 첫번째로 진로순서가 되고 3의 값이 세번째 순서가 된다는 뜻
[sotred_emergency.index(i) + 1 for i in emergency] # 응급도 값에 따라 진로 순서를 출력

# 정렬된 리스트에서 원본 리스트의 값의 인덱스를 찾음

[3, 1, 2]

In [6]:
data = ['제주', '경기', '전주'] # 원하는 출력 값 = ['064', '031', '063']
data2 = {
    '제주' : '064',
    '경기' : '031',
    '전주' : '063'
}

[data2[i] for i in data]

['064', '031', '063']

# 10. 가까운 수
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120890

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120890
# 가까운 수
# 입력한 값과 가장 가까운 수를 반환한다. 가장 가까운 수가 여러 개일 경우 더 작은 수를 return 합니다. (예: 입력값 20일때 [10, 30] 이라면 10 반환)
# 10.1

# [3, 10, 28] => [17, 10, 8] # 20과의 차이 값
# 원하는 숫자: 20 -> 20과 가까운 수를 입력하면 28이 제일 가까워서 28을 출력
# result: 28

In [7]:
l = [3, 10, 28]
sorted(l, key=lambda x:abs(x-20))[0] # 숫자 20과의 거리가 가장 가까운 순으로 리스트 정렬 후 가장 가까운 숫자 출력

[28, 10, 3]

In [15]:
l = [3, 10, 28, 30, 12]
sorted(l, key=lambda x:(abs(x-20), x))[0] # 앞조건으로 판별이 안되면 뒤 조건으로 편발한다(abs(x-20), x)

12

In [17]:
# 정답
# 가장 가까운 수가 여러 개일 경우 더 작은 수를 return 합니다.
# [3, 10, 28, 30, 12] => [17, 10, 8, 10, 8]
# [3, 10, 28, 30, 12] => [(17, 3), (10, 10), (8, 28), (10, 30), (8, 12)] # 이런식으로 만들어야한다.
# (8, 28), (8, 12) 가 뽑힐 것이고 그중 값이 낮은 12가 출력되어야한다.


def solution(array, n):
    return sorted(array, key=lambda x:(abs(x-20), x))[0] # 만약 abs(x-20)의 값이 여러개라면, x가 작은 값을 뽑겠다 -> 앞의 조건이 동일한게 있다면 뒤의 조건으로 한번더 판별하겠다.

solution([3, 10, 28, 30, 12], 20)

12

In [19]:
# 더 큰수를 출력하려면
def solution(array, n):
    return sorted(array, key=lambda x:(abs(x-20), n-x))[0]
    # 첫번째 값이 같았을 때 뒤의 값이 더 큰 값을 출력하겠다
    # abs(28-20) 과 abs(12-20) 은 8 / 동일 값이니 n-x의 조건으로 판단 -> 20-28 = -8, 20-12 = 8 / 따라서 정렬하면 -8값인 28이 앞으로 정렬됨

solution([3, 10, 28, 30, 12], 20)

28

In [ ]:
# list는 메모리 연속성이 없고 array는 메모리 연속성이 있다 -> array는 메모리가 순서대로 연결되어있는데 list는 가리키는 값만 가지고 있다

# 11. k의 개수
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120887

In [26]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120887
# k의 개수
# 1부터 13까지의 수에서, 1은 1, 10, 11, 12, 13 이렇게 총 6번 등장
# i부터 j까지 k가 몇 번 등장하는지 return 하도록 solution 함수를 완성

# 11.1
# i	 j	 k	 result
# 1	 13	 1	 6      # 1~13까지 1(k)은 총 6번 출력됨

i = 1
j = 13
k = 1

# 리스트에 해당 값들을 넣고 리스트 자체를 string으로 바꿈 -> 출력값:'[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]' => 리스트가 아니라 문자열 그 자체임
str(list(range(i, j+1))).count(str(k)) # 해당 문자열에서 k의 개수를 호출

6

In [27]:
# 정답
def solution(i, j, k):
    return str(list(range(i, j+1))).count(str(k))

solution(1,13,1)

6

In [30]:
# 순회

i = 1
j = 13
k = 1

count = 0
for temp in range(i, j + 1):
    count += str(temp).count(str(k))

count

6

# 직접 출제 문제

In [34]:
# 각 선분이 있는 곳에 총 길이 합을 구하라
# 0~5의 선분, 3~5의 선분, 7~10의 선분
[[0, 5], [3, 5], [7, 10]]

선 = [False] * 10

# 0~5의 선분
for i in range(0, 5):
    선[i] = True
print(선)

# 3~5의 선분
for i in range(3, 5):
    선[i] = True
print(선)

# 7~10의 선분
for i in range(7, 10):
    선[i] = True
print(선)

sum(선) # 정답    ->    0~5 선분의 길이 = 5 , 3~5선분의 길이는 0~5에 포함되어 있음, 7~10 선분의 길이 = 3
# 따라서 5 + 3 = 8

# ----- -----
# 12345
# -----
#   345
# ------ ---
#        789

[True, True, True, True, True, False, False, False, False, False]
[True, True, True, True, True, False, False, False, False, False]
[True, True, True, True, True, False, False, True, True, True]


8

In [35]:
# 에라토스테스트의 체 => 소수판별하는 것 => 이것을 알고리즘 문제로 내는 것은 강사님은 반대...

소수 = [True] * 120 # 120  : 에라토스테스트의 체 알고리즘 확인하면 120 확인 가능
소수[0] = 소수[1] = False # 0과 1은 소수가 아님

for i in range(4, 120, 2): # 2의 배수는 소수가 아님을 처리(2만 소수)
    소수[i] = False

for i in range(6, 120, 3): # 3의 배수는 소수가 아님을 처리
    소수[i] = False

# 4의 배수는 2의 배수에 속하기 때문에 4의 배수 처리는 할 필요 없다.

# ... 언제까지 처리해야할까..?
# 11보다 작은수의 배수만 지워도 충분하다고 적혀있음

# 참고
# https://nahwasa.com/entry/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98-%EC%B2%B4-%ED%98%B9%EC%9D%80-%EC%86%8C%EC%88%98%ED%8C%90%EC%A0%95-%EC%8B%9C-%EC%A0%9C%EA%B3%B1%EA%B7%BC-%EA%B9%8C%EC%A7%80%EB%A7%8C-%ED%99%95%EC%9D%B8%ED%95%98%EB%A9%B4-%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

[False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [ ]:
# 곱해지는 각 자연수중 하나는 무조건
# 제곱근과 같거나 작아야하는거니까

# 4 * 4
# 2 * 8

# 2, 3, 4

# 2, 4, 6, 8, 10, 12
# 3, 6, 9, 12
# ---
# 5, 10, 15

In [ ]:
for 소수, 판별 in enumerate(소수):
    if 판별:
        print(소수)

# pyalgo
링크 : https://100.pyalgo.co.kr/?page=23

In [38]:
# 2차원 배열과 타겟 숫자가 주어집니다. 주어진 2차원 배열에서 타겟 숫자가 존재하는지 확인하고, 존재하는 경우 True를, 존재하지 않는 경우 False를 반환

s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
print(sum(s, [])) # 초기값 []를 선언하여 s의 2차원 배열을 1차원 리스트로 만든다.
7 in sum(s, [])

[1, 3, 5, 7, 9, 11, 13, 15, 17]


True

In [39]:
# 행렬의 연산과 같은 것은 np를 사용하면 쉽고 빠르게 풀 수 있다.
import numpy as np

x = np.array([1,2,3]) # 배열의 곱 가능
x * 2

array([2, 4, 6])

In [40]:
s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
s = np.array(s)
np.where(s==7) # 7의 값이 어느 위치에 있는지 확인 가능

(array([1]), array([0]))

In [42]:
s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
s = np.array(s)
rows, cols = np.where(s==7) # 7의 값이 어느 위치에 있는지 확인하고 언패킹(행, 열의 값으로 반환)

rows, cols

(array([1]), array([0]))

In [43]:
# 지뢰찾기
x = [[0, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
]

x = np.array(x)
np.where(x==1) # 1이 존재하는 위치를 전부 출력

(array([0, 1, 2]), array([1, 1, 3]))

In [44]:
# 순회

x = [[0, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
]

s = 0
for i in x:
    s+=i.count(1)

3

In [46]:
x = [[0, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
]

x = np.array(x)
x == 1 # x에 x의 값이 1인것을 True로 반환

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [47]:
x = [[0, 5, 2, 0],
     [0, 7, 0, 6],
     [0, 1, 3, 5]]

x = np.array(x)
x > 3 # 3보다 큰 값만 True

array([[False,  True, False, False],
       [False,  True, False,  True],
       [False, False, False,  True]])