<a href="https://colab.research.google.com/github/Um-king/orm/blob/main/%5B%EB%AA%A8%EB%91%90%EC%97%B0%5D_2%EC%A3%BC%EC%B0%A8_3%EC%9D%BC_%EC%8B%9C%ED%80%80%EC%8A%A4%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 시퀀스 자료형

In [2]:
# 1.1 인덱싱

example = 'abcde'
print(example[0]) # 출력 : a
print(example[2]) # 출력 : c

# 마이너스 인덱스일 경우 역순
print(example[-1]) # 출력 : e

a
c
e


In [5]:
# 1.2 슬라이싱

example = 'abcde'
print(example[1:3]) # 출력: bc, (마지막 - 1)까지 슬라이싱
print(example[-4:-1]) # -4 위치부터 -2위치까지

print(range(10)[3]) # 출력: 3
print(range(100)[::5]) # 출력: range(0, 100, 5)

bc
bcd
3
range(0, 100, 5)


In [9]:
# 1.3 특정항목 포함 여부

example = 'abcde'
print('a' in example) # 출력: True
print('z' in example) # 출력: False
print('z' not in example) # 출력: True

True
False
True


In [10]:
# 1.4 연결 & 반복

example1 = 'abcde'
example2 = 'f'
print(example1 + example2) # 출력: abcdef
print(example2 * 3)        # 출력: fff

abcdef
fff


In [11]:
# 1.5 내장함수

example = 'abcde'
print(len(example))  # 출력: 5 -> 문자열의 길이
print(min(example))  # 출력: a -> 문자열의 최소값
print(max(example))  # 출력: e -> 문자열의 최대값

5
a
e


# 2. 시퀀스 자료형의 패킹과 언패킹

In [13]:
# 2.1 튜플 패킹

packed_tuple = 1, 2, 3, 4 # 콤마로 여러가지 값을 썼을 뿐인데 하나의 튜플로 만들어진다.
print(packed_tuple)  # 출력: (1, 2, 3, 4)
type(packed_tuple)

(1, 2, 3, 4)


tuple

In [15]:
# 2.2 언패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4

# 튜플 언패킹(각각의 인덱스 위치의 값을 새로운 변수에 각각 할당)
a, b, c, d = packed_tuple # 튜플로 패킹된 시퀀스를 순서대로 각각의 변수에 할당
print(a)  # 출력: 1
print(b)  # 출력: 2
print(c)  # 출력: 3
print(d)  # 출력: 4


1
2
3
4


In [19]:
# 다양한 패킹/언패킹

# range()는 0부터 n-1까지 숫자를 생성하는 함수!

a, b, c = range(3) # 범위 설정. 0~2까지 범위의 값을 변수에 할당(설정된 마지막값 - 1까지 범위 설정)
print(a, b, c)

0 1 2


In [20]:
# 언패킹
a, b, c, d, e = 'hello'

print(a)
print(b)
print(c)
print(d)
print(e)

h
e
l
l
o


In [21]:
# 언패킹
a, b = [10, 20]

print(a)
print(b)

10
20


In [22]:
# 별표를 이용한 언패킹
first, *middle, last = [1,2,3,4,5]
print(first) # 정수값으로 언패킹
print(middle) # 리스트로 묶임 -> 리스트로 언패킹
print(last) # 정수값으로 언패킹

1
[2, 3, 4]
5


In [23]:
# 별표를 이용한 언패킹
# 마지막 변수가 별표를 이용한 변수라면 마지막 값까지 리스트로 묶임
first, *middle = [1,2,3,4,5]
print(first) # 정수값으로 언패킹
print(middle) # 리스트로 묶임 -> 리스트로 언패킹

1
[2, 3, 4, 5]


In [24]:
# 별표를 이용한 언패킹
# 마지막 last변수에 마지막인덱스 값이 들어가고 나머지는 리스트로 묶임
*middle, last = [1,2,3,4,5]
print(middle) # 리스트로 묶임 -> 리스트로 언패킹
print(last) # 정수값으로 언패킹


[1, 2, 3, 4]
5


# 2. 리스트

In [27]:
# 리스트의 장점 : 여러가지 자료형을 넣을 수 있다.

z = [1, 'apple', 2.5, ['a', 'b'], (1, 2)]

print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])


1
apple
2.5
['a', 'b']
(1, 2)


In [28]:
# 2.2 리스트 값 수정

a = [1, 2, 3, 4, 5]
a[0] = 10000 # 인덱싱 설정 -> 새로운 값 할당
print(a)

[10000, 2, 3, 4, 5]


In [29]:
# 문자열은 변경할 수 없다!
s = 'licat'
print(s[0])
s[0] = 'k'

l


TypeError: ignored

In [30]:
# 2.3 리스트안에 리스트(다차원 리스트)

b = [[10, 20, 30], [1, 2, 3]]
print(b[1][2]) # 출력: 3 -> b[1][2] : b 리스트의 1 인덱스 위치의 리스트의 2 인덱스 위치의 값 출력

3


In [33]:
print(b)
print(b[0])
print(b[1])
print(b[0][0])

[[10, 20, 30], [1, 2, 3]]
[10, 20, 30]
[1, 2, 3]
10


In [34]:
# 리스트의 덧셈

a = [1, 2, 3, 4, 5] # + [6, 7, 8]
b = [6, 7, 8]

print(a + b) # 출력: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [35]:
# 리스트 덧셈이 너무 당연하게 요소를 붙이는 것이다라고 생각하지 않으셨으면 좋겠습니다.
# numpy 사용 시 리스트가 이어 붙여지는것이 아님

import numpy as np

l = [1, 2, 3]
l = np.array(l) # array : numpy 라이브러리에서 사용하는 리스트

print(l)
print(l * 3)
print(l + l)

[1 2 3]
[3 6 9]
[2 4 6]


In [36]:
# 0~4번째 인덱스까지 출력 가능하므로 범위가 벗어나 에러!

lst = [1, 2, 3, 4, 5]
print(lst[10])

IndexError: ignored

In [37]:
# 슬라이싱 실습!

l = [1, 2, 3, 4, 5]
print(l[:])     # 출력: [1, 2, 3, 4, 5] -> 전체 출력
print(l[::-1])  # 출력: [5, 4, 3, 2, 1] -> 역순 출력
print(l[::2])   # 출력: [1, 3, 5] -> 처음부터 마지막까지 2칸씩 출력
print(l[0:4][::-1]) # 출력: [3, 2, 1] -> 슬라이싱 n번 사용 가능 -> 0~3번째 인덱스 슬라이싱 후 역순 출력

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
[1, 3, 5]
[4, 3, 2, 1]
